def throw_exception5():
    # This function will throw a custom exception
    raise Exception("Custom exception from helper5")
