def throw_exception1():
    raise Exception("This is Exception 1 from helper1")
